export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS'
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE'

export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS'
export const CREATE_STUDENT_FAILURE = 'CREATE_STUDENT_FAILURE'

export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS'
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE'

export const EDIT_STUDENT_SUCCESS = 'EDIT_STUDENT_SUCCESS'
export const EDIT_STUDENT_FAILURE = 'EDIT_STUDENT_FAILURE'

export const INVOICE_STUDENT_SUCCESS = 'INVOICE_STUDENT_SUCCESS'
export const INVOICE_STUDENT_FAILURE = 'INVOICE_STUDENT_FAILURE'

export const LIST_CLASSROOMS_SUCCESS = 'LIST_CLASSROOMS_SUCCESS'
export const LIST_CLASSROOMS_FAILURE = 'LIST_CLASSROOMS_FAILURE'

export const STUDENTS_CLASSROOMS_SUCCESS = 'STUDENTS_CLASSROOMS_SUCCESS'
export const STUDENTS_CLASSROOMS_FAILURE = 'STUDENTS_CLASSROOMS_FAILURE'

export const SIGN_CLASSROOMS_SUCCESS = 'SIGN_CLASSROOMS_SUCCESS'
export const SIGN_CLASSROOMS_FAILURE = 'SIGN_CLASSROOMS_FAILURE'